// <auto-generated />
using System;
using AuditManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditManagement.API.Migrations
{
    [DbContext(typeof(AuditSystemDbContext))]
    [Migration("20260318100244_AddExpertiseFieldToUsers")]
    partial class AddExpertiseFieldToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditManagement.API.Models.Audit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("AuditCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AuditName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AuditorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("AuditId")
                        .HasName("PK__Audits__A17F23989E4364B0");

                    b.HasIndex("AuditorId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("AuditManagement.API.Models.CorrectiveAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ObservationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ActionId")
                        .HasName("PK__Correcti__FFE3F4D944E8A319");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ObservationId");

                    b.ToTable("CorrectiveActions");
                });

            modelBuilder.Entity("AuditManagement.API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BEDF8892A9B");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AuditManagement.API.Models.Observation", b =>
                {
                    b.Property<int>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservationId"));

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ObservationId")
                        .HasName("PK__Observat__420EA5E75E566500");

                    b.HasIndex("AuditId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("AuditManagement.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Expertise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C36F518A3");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534EE561002")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AuditManagement.API.Models.Audit", b =>
                {
                    b.HasOne("AuditManagement.API.Models.User", "Auditor")
                        .WithMany("AuditAuditors")
                        .HasForeignKey("AuditorId")
                        .IsRequired()
                        .HasConstraintName("FK__Audits__AuditorI__693CA210");

                    b.HasOne("AuditManagement.API.Models.User", "CreatedByUser")
                        .WithMany("AuditCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK__Audits__CreatedB__6A30C649");

                    b.HasOne("AuditManagement.API.Models.Department", "Department")
                        .WithMany("Audits")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Audits__Departme__68487DD7");

                    b.Navigation("Auditor");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AuditManagement.API.Models.CorrectiveAction", b =>
                {
                    b.HasOne("AuditManagement.API.Models.User", "AssignedToUser")
                        .WithMany("CorrectiveActions")
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("FK__Correctiv__Assig__74AE54BC");

                    b.HasOne("AuditManagement.API.Models.Observation", "Observation")
                        .WithMany("CorrectiveActions")
                        .HasForeignKey("ObservationId")
                        .IsRequired()
                        .HasConstraintName("FK__Correctiv__Obser__73BA3083");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("AuditManagement.API.Models.Observation", b =>
                {
                    b.HasOne("AuditManagement.API.Models.Audit", "Audit")
                        .WithMany("Observations")
                        .HasForeignKey("AuditId")
                        .IsRequired()
                        .HasConstraintName("FK__Observati__Audit__6EF57B66");

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("AuditManagement.API.Models.User", b =>
                {
                    b.HasOne("AuditManagement.API.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Users__Departmen__628FA481");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AuditManagement.API.Models.Audit", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("AuditManagement.API.Models.Department", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AuditManagement.API.Models.Observation", b =>
                {
                    b.Navigation("CorrectiveActions");
                });

            modelBuilder.Entity("AuditManagement.API.Models.User", b =>
                {
                    b.Navigation("AuditAuditors");

                    b.Navigation("AuditCreatedByUsers");

                    b.Navigation("CorrectiveActions");
                });
#pragma warning restore 612, 618
        }
    }
}
